on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  tfapply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: true
      env:
        TF_VAR_grafana_url: ${{ secrets.GRAFANA_URL }}
        TF_VAR_grafana_access_token: ${{ secrets.GRAFANA_ACCESS_TOKEN }}
        TF_VAR_oncall_url: ${{ secrets.ONCALL_URL }}
        TF_VAR_oncall_access_token: ${{ secrets.ONCALL_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
