on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
jobs:
  tfplan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      env:
        TF_VAR_grafana_url: ${{ secrets.GRAFANA_URL }}
        TF_VAR_grafana_access_token: ${{ secrets.GRAFANA_ACCESS_TOKEN }}
        TF_VAR_oncall_url: ${{ secrets.ONCALL_URL }}
        TF_VAR_oncall_access_token: ${{ secrets.ONCALL_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}


    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        VALIDATE_STDOUT: "${{ steps.validate.outputs.stdout }}"
        INIT_OUTCOME: "${{ steps.init.outcome }}"
        VALIDATE_OUTCOME: "${{ steps.validate.outcome }}"
        FMT_OUTCOME: "${{ steps.fmt.outcome }}"
        PLAN_OUTCOME: "${{ steps.plan.outcome }}"
        GITHUB_ACTOR: "${{ github.actor }}"
        GITHUB_WORKFLOW: "${{ github.workflow }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
          })

          // 2. Prepare format of the comment
          const output = `#### Terraform Format and Style 🖌\`${ process.env.FMT_OUTCOME }\`
          #### Terraform Initialization ⚙️\`${ process.env.INIT_OUTCOME }\`
          #### Terraform Validation 🤖\`${ process.env.VALIDATE_OUTCOME }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${process.env.VALIDATE_STDOUT}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${ process.env.PLAN_OUTCOME }\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${ process.env.GITHUB_ACTOR }, Action: \`${{ github.event_name }}\`, Workflow: \`${ process.env.GITHUB_WORKFLOW }\`*`;

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
